apiVersion: v1
kind: ConfigMap
metadata:
  name: wechat-auto-refresh-server
  namespace: nilorg
data:
  config.yaml: |
    redis:
      address: "localhost:6379"
      password: ""
      db: 0

    apps:
      - id: xxxx
        secret: "ssss"
        refresh_duration: 3600
        redis_access_token_key: "nilorg:wechat:xxxx:token"
        redis_js_api_ticket_key: "nilorg:wechat:xxxx:ticket"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat-auto-refresh-server
  namespace: nilorg
spec:
  selector:
    matchLabels:
      app: wechat-auto-refresh-server
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: wechat-auto-refresh-server
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: wechat-auto-refresh-server
          image: nilorg/wechat-auto-refresh-server:latest
          imagePullPolicy: Always
